---
deployment:
  tasks:
    - source /home/wt29jctjbes9/virtualenv/ulisting/3.7/bin/activate && cd /home/wt29jctjbes9/ulisting
    - pip install -r requirements.txt
    - python manage.py collectstatic --no-input
    - python manage.py migrate
    - touch tmp/restart.txt