# Generated by Django 3.2.6 on 2021-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listingCat',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
