# Generated by Django 3.2.6 on 2021-10-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcat',
            name='icon',
            field=models.CharField(default='im-icon-Chef-Hat', max_length=50),
            preserve_default=False,
        ),
    ]
