# Generated by Django 3.2.7 on 2021-12-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_country_wikidataid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='wikiDataId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='wikiDataId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
