# Generated by Django 3.2.7 on 2021-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_citylocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='citylocations',
            name='communitiny',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='citylocations',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
