# Generated by Django 3.2.7 on 2021-12-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211208_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cityLocations',
        ),
    ]
